// Sample data for timeline testing
// This contains the actual CSV data from Attachment Doc for testing purposes

export const sampleSalesData = [
  {
    "order-id": "408-4870009-9733125",
    "order-item-id": "5.23E+13",
    "purchase-date": "2025-07-30T08:34:47+00:00",
    "payments-date": "2025-07-30T08:34:47+00:00",
    "reporting-date": "2025-07-31T04:21:19+00:00",
    "promise-date": "2025-08-21T18:29:59+00:00",
    "days-past-promise": "-2",
    "buyer-email": "p3vkb18m93xc7lv@marketplace.amazon.in",
    "buyer-name": "Mandeep Dhillon",
    "buyer-phone-number": "9855161554",
    "sku": "ARB_B0B79CYVTM",
    "product-name": "VSN Noise Gate Pedal, Noise Killer Guitar Pedal Noise Suppressor Effect for Electric Guitar and Bass True Bypass",
    "quantity-purchased": "1",
    "quantity-shipped": "0",
    "quantity-to-ship": "1",
    "ship-service-level": "Standard",
    "recipient-name": "Mandeep Dhillon",
    "ship-address-1": "6368 Ground Floor",
    "ship-address-2": "Rajiv Vihar, Manimajra",
    "ship-address-3": "",
    "ship-city": "CHANDIGARH",
    "ship-state": "CHANDIGARH",
    "ship-postal-code": "160101",
    "ship-country": "IN",
    "is-business-order": "FALSE",
    "purchase-order-number": "",
    "price-designation": "",
    "is-iba": "FALSE",
    "verge-of-cancellation": "FALSE",
    "verge-of-lateShipment": "FALSE"
  },
  {
    "order-id": "404-8712750-6212352",
    "order-item-id": "5.24E+13",
    "purchase-date": "2025-07-31T23:57:52+00:00",
    "payments-date": "2025-07-31T23:57:52+00:00",
    "reporting-date": "2025-08-01T00:27:39+00:00",
    "promise-date": "2025-08-22T18:29:59+00:00",
    "days-past-promise": "-3",
    "buyer-email": "4g6l85kyf1hj3gs@marketplace.amazon.in",
    "buyer-name": "Meghna",
    "buyer-phone-number": "9686372602",
    "sku": "ARB_B084SDXVBD",
    "product-name": "Polaroid Color Film for I-Type (6000)",
    "quantity-purchased": "1",
    "quantity-shipped": "0",
    "quantity-to-ship": "1",
    "ship-service-level": "Standard",
    "recipient-name": "Meghna Aravind",
    "ship-address-1": "6A Annaiah Reddy Layout 30th Main Road",
    "ship-address-2": "JP Nagar 6th phase Saralki Village",
    "ship-address-3": "",
    "ship-city": "BENGALURU",
    "ship-state": "KARNATAKA",
    "ship-postal-code": "560078",
    "ship-country": "IN",
    "is-business-order": "FALSE",
    "purchase-order-number": "",
    "price-designation": "",
    "is-iba": "FALSE",
    "verge-of-cancellation": "FALSE",
    "verge-of-lateShipment": "FALSE"
  },
  {
    "order-id": "408-1498953-3866768",
    "order-item-id": "5.25E+13",
    "purchase-date": "2025-08-01T04:51:58+00:00",
    "payments-date": "2025-08-01T04:51:58+00:00",
    "reporting-date": "2025-08-01T05:22:11+00:00",
    "promise-date": "2025-08-22T18:29:59+00:00",
    "days-past-promise": "-3",
    "buyer-email": "pqqwbvjykpr4v0b@marketplace.amazon.in",
    "buyer-name": "Venkatesh Nagan",
    "buyer-phone-number": "9971066445",
    "sku": "ARB_B00FJ2WOJE",
    "product-name": "OSTENT 850mAh Rechargeable Lithium-ion Battery + Tool Pack Kit Compatible for Nintendo GBA SP [Game Boy Advance]",
    "quantity-purchased": "1",
    "quantity-shipped": "0",
    "quantity-to-ship": "1",
    "ship-service-level": "Standard",
    "recipient-name": "Venkatesh Nagan",
    "ship-address-1": "Flat No. M2, Builtech Greens Apartments,",
    "ship-address-2": "Manapullikavu",
    "ship-address-3": "",
    "ship-city": "PALAKKAD",
    "ship-state": "KERALA",
    "ship-postal-code": "678013",
    "ship-country": "IN",
    "is-business-order": "FALSE",
    "purchase-order-number": "",
    "price-designation": "",
    "is-iba": "FALSE",
    "verge-of-cancellation": "FALSE",
    "verge-of-lateShipment": "FALSE"
  }
];

export const samplePurchaseData = [
  {
    "Order Date": "08/18/2025",
    "Order ID": "112-1815601-9677016",
    "Account Group": "FIGUREOUT INC",
    "PO Number": "",
    "Order Quantity": "1",
    "Currency": "USD",
    "Order Subtotal": "26.95",
    "Order Shipping & Handling": "0",
    "Order Promotion": "0",
    "Order Tax": "0",
    "Order Net Total": "26.95",
    "Order Status": "Pending Fulfillment",
    "Approver": "",
    "Account User": "FIGUREOUT ENTERPRISES",
    "Account User Email": "b2b@figurout.com",
    "Shipment Date": "08/18/2025",
    "Shipment Status": "Shipping Soon",
    "Delivery Status": "",
    "Expected Delivery Date": "08/19/2025",
    "Carrier Tracking #": "",
    "Shipment Quantity": "1",
    "Shipping Address": "PoshACE-Tech, 472 AMHERST ST UNIT 7904445, NASHUA, 03063-1204, NH, US",
    "Shipment Subtotal": "26.95",
    "Shipment Shipping & Handling": "0",
    "Shipment Promotion": "",
    "Shipment Tax": "0",
    "Shipment Net Total": "26.95",
    "Carrier Name": "",
    "Amazon-Internal Product Category": "CE",
    "ASIN": "B0B79CYVTM",
    "Title": "Avantree C81-Gaming - USB-C Bluetooth 5.3 Audio Adapter for PS5, Qualcomm Chip, aptX Adaptive & HD, Premium Sound, Works with AirPods, Bose Headphones & More",
    "UNSPSC": "43211614",
    "Segment": "Information Technology Broadcasting and Telecommunications",
    "Family": "Computer Equipment and Accessories",
    "Class": "Computer accessories",
    "Commodity": "Bluetooth universal serial bus USB adapter",
    "Brand Code": "AVANG",
    "Brand": "Avantree",
    "Manufacturer": "Avantree",
    "National Stock Number": "",
    "Item model number": "BTDG-C81",
    "Part number": "BTDG-C81-G",
    "Product Condition": "New",
    "Company Compliance": "",
    "Listed PPU": "N/A",
    "Purchase PPU": "26.95",
    "Item Quantity": "1",
    "Item Subtotal": "26.95",
    "Item Shipping & Handling": "0",
    "Item Promotion": "",
    "Item Tax": "0",
    "Item Net Total": "26.95",
    "PO Line Item Id": "",
    "Tax Exemption Applied": "No",
    "Tax Exemption Type": "",
    "Tax Exemption Opt Out": "No",
    "Pricing Savings program": "N/A",
    "Pricing Discount Applied": "0",
    "Receiving Status": "",
    "Received Quantity": "",
    "Received Date": "",
    "Receiver Name": "N/A",
    "Receiver Email": "",
    "GL Code": "",
    "Department": "",
    "Cost Center": "",
    "Project Code": "",
    "Location": "",
    "Custom Field 1": "",
    "Seller Name": "AvantreeDirect USA",
    "Seller Credentials": "Registered Small Business, 889 certification, Classified Small Business - SBA Standard"
  },
  {
    "Order Date": "08/18/2025",
    "Order ID": "112-2869753-7173057",
    "Account Group": "FIGUREOUT INC",
    "PO Number": "",
    "Order Quantity": "1",
    "Currency": "USD",
    "Order Subtotal": "9.99",
    "Order Shipping & Handling": "0",
    "Order Promotion": "0",
    "Order Tax": "0",
    "Order Net Total": "9.99",
    "Order Status": "Pending Fulfillment",
    "Approver": "",
    "Account User": "FIGUREOUT ENTERPRISES",
    "Account User Email": "b2b@figurout.com",
    "Shipment Date": "08/18/2025",
    "Shipment Status": "Shipping Soon",
    "Delivery Status": "",
    "Expected Delivery Date": "08/19/2025",
    "Carrier Tracking #": "",
    "Shipment Quantity": "1",
    "Shipping Address": "PoshACE-Tech, 472 AMHERST ST UNIT 7904445, NASHUA, 03063-1204, NH, US",
    "Shipment Subtotal": "9.99",
    "Shipment Shipping & Handling": "0",
    "Shipment Promotion": "",
    "Shipment Tax": "0",
    "Shipment Net Total": "9.99",
    "Carrier Name": "",
    "Amazon-Internal Product Category": "CE",
    "ASIN": "B084SDXVBD",
    "Title": "pzoz Earbuds Case Compatible for Apple iPhone/iPad/iPods EarPods, Earphones Cord Organizer Cover Wired Manager Holder Wrap Winder Mini Storage Carrying Cable Management (Earbuds)",
    "UNSPSC": "43191607",
    "Segment": "Information Technology Broadcasting and Telecommunications",
    "Family": "Communications Devices and Accessories",
    "Class": "Personal communications device accessories or parts",
    "Commodity": "Phone headset ear or speaker cushions",
    "Brand Code": "",
    "Brand": "pzoz",
    "Manufacturer": "PZOZ",
    "National Stock Number": "",
    "Item model number": "earbuds",
    "Part number": "pzoz-earbud case",
    "Product Condition": "New",
    "Company Compliance": "",
    "Listed PPU": "N/A",
    "Purchase PPU": "9.99",
    "Item Quantity": "1",
    "Item Subtotal": "9.99",
    "Item Shipping & Handling": "0",
    "Item Promotion": "",
    "Item Tax": "0",
    "Item Net Total": "9.99",
    "PO Line Item Id": "",
    "Tax Exemption Applied": "No",
    "Tax Exemption Type": "",
    "Tax Exemption Opt Out": "No",
    "Pricing Savings program": "N/A",
    "Pricing Discount Applied": "0",
    "Receiving Status": "",
    "Received Quantity": "",
    "Received Date": "",
    "Receiver Name": "N/A",
    "Receiver Email": "",
    "GL Code": "",
    "Department": "",
    "Cost Center": "",
    "Project Code": "",
    "Location": "",
    "Custom Field 1": "",
    "Seller Name": "Joyce Young-US",
    "Seller Credentials": ""
  },
  {
    "Order Date": "08/18/2025",
    "Order ID": "112-5787295-6350602",
    "Account Group": "FIGUREOUT INC",
    "PO Number": "",
    "Order Quantity": "1",
    "Currency": "USD",
    "Order Subtotal": "8.54",
    "Order Shipping & Handling": "0",
    "Order Promotion": "0",
    "Order Tax": "0",
    "Order Net Total": "8.54",
    "Order Status": "Pending Fulfillment",
    "Approver": "",
    "Account User": "FIGUREOUT ENTERPRISES",
    "Account User Email": "b2b@figurout.com",
    "Shipment Date": "08/18/2025",
    "Shipment Status": "Shipping Soon",
    "Delivery Status": "",
    "Expected Delivery Date": "08/22/2025",
    "Carrier Tracking #": "",
    "Shipment Quantity": "1",
    "Shipping Address": "PoshACE-Tech, 472 AMHERST ST UNIT 7904445, NASHUA, 03063-1204, NH, US",
    "Shipment Subtotal": "8.54",
    "Shipment Shipping & Handling": "0",
    "Shipment Promotion": "",
    "Shipment Tax": "0",
    "Shipment Net Total": "8.54",
    "Carrier Name": "",
    "Amazon-Internal Product Category": "CE",
    "ASIN": "B00FJ2WOJE",
    "Title": "Treedix 4 Pcs RJ45 8-pin Connector (8P8C) and Breakout Board Kit Compatible with Ethernet DMX-512 RS-485 RS-422 RS-232 (Unassambled)",
    "UNSPSC": "43200000",
    "Segment": "Information Technology Broadcasting and Telecommunications",
    "Family": "Components for information technology or broadcasting or telecommunications",
    "Class": "Components for information technology or broadcasting or telecommunications",
    "Commodity": "Components for information technology or broadcasting or telecommunications",
    "Brand Code": "",
    "Brand": "Treedix",
    "Manufacturer": "Treedix",
    "National Stock Number": "",
    "Item model number": "",
    "Part number": "",
    "Product Condition": "New",
    "Company Compliance": "",
    "Listed PPU": "N/A",
    "Purchase PPU": "8.54",
    "Item Quantity": "1",
    "Item Subtotal": "8.54",
    "Item Shipping & Handling": "0",
    "Item Promotion": "",
    "Item Tax": "0",
    "Item Net Total": "8.54",
    "PO Line Item Id": "",
    "Tax Exemption Applied": "No",
    "Tax Exemption Type": "",
    "Tax Exemption Opt Out": "No",
    "Pricing Savings program": "N/A",
    "Pricing Discount Applied": "0",
    "Receiving Status": "",
    "Received Quantity": "",
    "Received Date": "",
    "Receiver Name": "N/A",
    "Receiver Email": "",
    "GL Code": "",
    "Department": "",
    "Cost Center": "",
    "Project Code": "",
    "Location": "",
    "Custom Field 1": "",
    "Seller Name": "Treedix",
    "Seller Credentials": ""
  }
];
