name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Typecheck
        run: npm run typecheck
        
      - name: Lint
        run: npm run lint
        
      - name: Unit tests
        run: npm run test:unit
        
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        
      - name: E2E smoke (Chromium)
        run: npm run e2e:smoke -- --project=chromium --trace=on
        
      - name: E2E full (Chromium)
        run: npm run e2e:full
        
      - name: Build
        run: npm run build
        
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          if-no-files-found: ignore
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: dist/
