name: Nightly CI

on:
  schedule:
    - cron: "0 2 * * *"   # 02:00 UTC nightly
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "20"
          cache: "npm"
          
      - name: Install dependencies
        run: npm ci
        
      - name: Typecheck
        run: npm run typecheck
        
      - name: Unit tests
        run: npm run test:unit
        
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        
      - name: E2E smoke tests
        run: npm run e2e:smoke -- --project=chromium --trace=on
        
      - name: Build
        run: npm run build
        
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nightly-playwright-report
          path: playwright-report/
          if-no-files-found: ignore
