name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (e.g. 1.0.2)"
        required: true

jobs:
  cut-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Read CHANGELOG
        id: notes
        run: |
          awk 'f;/^## /{f=1} /^## / && NR>1{exit}' CHANGELOG.md | tail -n +2 > notes.md
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          cat notes.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
      - name: Create Git tag
        run: |
          git config user.name "ci-bot"
          git config user.email "ci@example.com"
          sed -i "s/APP_VERSION = \".*\"/APP_VERSION = \"${{ github.event.inputs.version }}\"/g" src/lib/version.ts
          git add src/lib/version.ts
          git commit -m "chore(release): v${{ github.event.inputs.version }}"
          git tag v${{ github.event.inputs.version }}
          git push --follow-tags
          
      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: v${{ github.event.inputs.version }}
          body: ${{ steps.notes.outputs.notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload build artifact to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
